name: Deploy to GitHub Pages (Preview)
concurrency: preview-${{ github.ref }}

on:
  pull_request:
    branches: "master"

jobs:
  build-preview:
    name: Build and Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -w apps/web
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: "./apps/web/build/"
